%% HRL file generated by ERLSOM
%%
%% It is possible (and in some cases necessary) to change the name of
%% the record fields.
%%
%% It is possible to add default values, but be aware that these will
%% only be used when *writing* an xml document.


-type anyAttrib()  :: {{string(),    %% name of the attribute
                        string()},   %% namespace
                       string()}.    %% value

-type anyAttribs() :: [anyAttrib()] | undefined.

%% xsd:QName values are translated to #qname{} records.
-record(qname, {uri :: string(),
                localPart :: string(),
                prefix :: string(),
                mappedPrefix :: string()}).



-record(current_observation, {anyAttribs :: anyAttribs(),
	version :: string() | undefined,
	credit :: string() | undefined,
	credit_URL :: string() | undefined,
	image :: imageType() | undefined,
	suggested_pickup :: string() | undefined,
	suggested_pickup_period :: integer() | undefined,
	location :: string() | undefined,
	station_id :: string() | undefined,
	latitude :: string() | undefined,
	longitude :: string() | undefined,
	elevation :: integer() | undefined,
	observation_time :: string() | undefined,
	observation_time_rfc822 :: string() | undefined,
	weather :: string() | undefined,
	temperature_string :: string() | undefined,
	temp_f :: string() | undefined,
	temp_c :: string() | undefined,
	water_temp_f :: string() | undefined,
	water_temp_c :: string() | undefined,
	relative_humidity :: integer() | undefined,
	wind_string :: string() | undefined,
	wind_dir :: string() | undefined,
	wind_degrees :: integer() | undefined,
	wind_mph :: string() | undefined,
	wind_gust_mph :: string() | undefined,
	wind_kt :: string() | undefined,
	wind_gust_kt :: string() | undefined,
	pressure_string :: string() | undefined,
	pressure_mb :: string() | undefined,
	pressure_in :: string() | undefined,
	pressure_tendency_mb :: string() | undefined,
	pressure_tendency_in :: string() | undefined,
	dewpoint_string :: string() | undefined,
	dewpoint_f :: string() | undefined,
	dewpoint_c :: string() | undefined,
	heat_index_string :: string() | undefined,
	heat_index_f :: integer() | undefined,
	heat_index_c :: integer() | undefined,
	windchill_string :: string() | undefined,
	windchill_f :: integer() | undefined,
	windchill_c :: integer() | undefined,
	visibility_mi :: string() | undefined,
	wave_height_m :: string() | undefined,
	wave_height_ft :: string() | undefined,
	dominant_period_sec :: integer() | undefined,
	average_period_sec :: string() | undefined,
	mean_wave_dir :: string() | undefined,
	mean_wave_degrees :: integer() | undefined,
	tide_ft :: string() | undefined,
	steepness :: string() | undefined,
	water_column_height :: string() | undefined,
	surf_height_ft :: string() | undefined,
	swell_dir :: string() | undefined,
	swell_degrees :: integer() | undefined,
	swell_period :: string() | undefined,
	icon_url_base :: string() | undefined,
	icon_name :: string() | undefined,
	two_day_history_url :: string() | undefined,
	icon_url_name :: string() | undefined,
	ob_url :: string() | undefined,
	disclaimer_url :: string() | undefined,
	copyright_url :: string() | undefined,
	privacy_policy_url :: string() | undefined}).

-type current_observation() :: #current_observation{}.


-record(imageType, {anyAttribs :: anyAttribs(),
	url :: string() | undefined,
	title :: string() | undefined,
	link :: string() | undefined}).

-type imageType() :: #imageType{}.